### ISSUE TITLE
Data type conversion for scalar value types from proto3 to JSON compliant datatypes

### ISSUE THREAD

**Issue by S-Eibl** [Interactions-HSG/grpcwot#15]
#### Actual implementation

The actual version of the CLI accepts only basic data types for scalar field types:

```
func fieldToDataSchema(f *proto.Field) wot.DataSchema {
	switch f.Type {
	case "bool":
		return wot.DataSchema{DataType: "boolean"}
	case "float":
		return wot.DataSchema{DataType: "number"}
	case "int32":
		return wot.DataSchema{DataType: "integer"}
	default:
		return wot.DataSchema{DataType: "string"}
	}
}
```

#### Goal

The CLI should be able to transform every scalar value type available for proto3 syntax denoted by https://developers.google.com/protocol-buffers/docs/proto3#scalar.

#### Acceptance criteria
- Each available scalar value type can be parsed
- The fields scalar type is converted to the correct type for JSON according to the table

**Comment by iomz** [comment]
>The fields scalar type is converted to the correct type for JSON according to the table

As I commented in #14, there's no JSON in the table.

**Comment by S-Eibl** [comment]
There is a conversion policy at the [proto3 docs](https://developers.google.com/protocol-buffers/docs/proto3#json), but it converts 64-bit numbers to strings. 
The problem with the Thing Description arises as it should express the type and format of a property. I would suggest bypassing this through [xsd types](https://www.ibm.com/docs/ru/jfsm/1.1.2.1?topic=queries-xsd-data-types). Then the originator can emit values for any kind, and the recipient can format it according to the "xsd" type. I would therefore change the table from above accordingly:
![image](https://user-images.githubusercontent.com/77973550/173252671-25b41c83-65ae-40b2-8271-d1935099c766.png)
Denoting the original type from proto syntax in TD's DataSchema would require an ontology for the proto3 scalar types, and I haven't found one which supports that. The other possibility would be to write in the proto3 types directly in the DataSchema. This only works if the client understands these types and a conversion schema for proto3 types is added in the nodewot. 
So the possibilities are:
- using the table from proto3 docs
- using xsd types 
- developing an ontology for proto3 scalar types
- expecting the client to be able to operate proto3 syntax and directly pasting the types

I prefer the xsd types; what do you think?

**Comment by iomz** [comment]
I'm not how the xsd annotations would solve the irreversible translation problem.

>The other possibility would be to write in the proto3 types directly in the DataSchema. This only works if the client understands these types and a conversion schema for proto3 types is added in the nodewot.

Why nodewot?

To do this in a proper way, I'd create a vocabulary for ProtoBuf's scalar value types. But since you are severely backlogged from the planned milestone now, I suggest you to keep the mapping as is and move foreward.
