### ISSUE TITLE
Derive RPCs and Messages

### ISSUE THREAD

**Issue by S-Eibl** [Interactions-HSG/grpcwot#3]
The [protoparser](https://github.com/emicklei/proto) should be used to get all RPC functions and Messages from a sample proto file. 
- Messages should be stored in a map with string key to be accessable by their name as the protoparser stores RPC function return and request types as strings
- rpcFunctions should be stored in a slice to have a collection that could be iterated

**Comment by iomz** [comment]
Again, why "should"?

Why are you recreating the intermediary map and slice instead of directly using the parsed elements?
https://pkg.go.dev/github.com/emicklei/proto#pkg-types
